export function randomPhrase() {
  const randomIndex = Math.floor(Math.random() * responses.length);
  return responses[randomIndex];
}

// const responses = ['long text, '];
const responses = [
  "In the grand scheme of things, it's important to consider all perspectives before making a decision.",
  'When we look at the bigger picture, we can see how interconnected all these issues are.',
  "It's crucial to weigh the pros and cons carefully to arrive at a balanced conclusion.",
  'By examining the details closely, we can uncover insights that might otherwise be overlooked.',
  'Taking a step back allows us to see the broader implications of our actions.',
  "It's essential to remain open-minded and consider alternative viewpoints.",
  'A thorough analysis can reveal underlying patterns and trends that inform our understanding.',
  'Engaging in thoughtful dialogue helps us to refine our ideas and reach a consensus.',
  'Reflecting on past experiences can provide valuable lessons for future decisions.',
  'Collaboration and cooperation are key to achieving our common goals.',
  "It's important to stay informed and up-to-date with the latest developments in the field.",
  'By fostering a culture of continuous learning, we can adapt to changing circumstances.',
  'Effective communication is vital for building strong relationships and trust.',
  'Innovation often arises from challenging the status quo and thinking outside the box.',
  "It's important to remain resilient and adaptable in the face of adversity.",
  'By setting clear objectives and priorities, we can stay focused and achieve our goals.',
  "It's essential to recognize and celebrate our successes, no matter how small.",
  'Constructive feedback helps us to grow and improve both personally and professionally.',
  'By embracing diversity and inclusion, we can create a more equitable and just society.',
  "It's important to maintain a healthy work-life balance to ensure long-term well-being.",
];
// const responses = [
//   "That's an interesting point.",
//   "I'll need to think about that.",
//   "Tell me more.",
//   "I understand your perspective.",
//   "That's a valid concern.",
//   "Can you elaborate on that?",
//   "I see what you mean.",
//   "That's a good question.",
//   "Let's explore that further.",
//   "I appreciate your input.",
//   "That's something to consider.",
//   "I'll take that into account.",
//   "That's a great observation.",
//   "I hadn't thought of it that way.",
//   "That's a compelling argument.",
//   "I'll need to look into that.",
//   "That's a fair point.",
//   "I can see why you think that.",
//   "That's an important issue.",
//   "I'll make a note of that.",
//   "That's a thoughtful comment.",
//   "I value your perspective.",
//   "That's a noteworthy point.",
//   "I'll consider that carefully.",
//   "That's a reasonable suggestion.",
// ];
